debug: true

spring:
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key.serializer: org.apache.kafka.common.serialization.StringSerializer
      value.serializer: io.cloudevents.kafka.CloudEventSerializer
