debug: true

spring:
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      # Alternatively, org.springframework.kafka.support.serializer.ErrorHandlingDeserializer + delegate
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.cloudevents.kafka.CloudEventDeserializer
